{% set name = "openlineage-sql" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openlineage_sql-{{ version }}.tar.gz
  sha256: 1d09ec960580840af74bc6149aca6f06a5416272ced1d51173939885c054ac7e

build:
  skip: true  # [py<38]
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.0
    - pip
  run:
    - python

test:
  imports:
    - openlineage_sql
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python interface for the Rust OpenLineage lineage extraction library
  home: https://github.com/OpenLineage/OpenLineage
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
extra:
  recipe-maintainers:
    - rxm7706
    - millsks
